https://stackoverflow.com/questions/18096783/using-distance-matrix-to-find-coordinate-points-of-set-of-points
https://math.stackexchange.com/questions/156161/finding-the-coordinates-of-points-from-distance-matrix

In [ ]:
import numpy as np

In [4]:
D = [[0,11,5,12,7,13,9,11],
[11,0,13,2,17,4,15,20],
[5,13,0,14,1,15,12,12],
[12,2,14,0,18,5,16,21],
[7,17,1,18,0,20,15,17],
[13,4,15,5,20,0,19,22],
[9,15,12,16,15,19,0,30],
[11,20,12,21,17,22,30,0]]

In [15]:
M=np.zeros_like(D, float)

In [17]:
for i in range(8):
    for j in range(8):
        d_1j=D[0][j]
        d_i1=D[i][0]
        d_ij=D[i][j]
        M[i][j]=1/2*(d_1j**2+d_i1**2-d_ij**2)

In [18]:
M

array([[   0. ,    0. ,    0. ,    0. ,    0. ,    0. ,    0. ,    0. ],
       [   0. ,  121. ,  -11.5,  130.5,  -59.5,  137. ,  -11.5,  -79. ],
       [   0. ,  -11.5,   25. ,  -13.5,   36.5,  -15.5,  -19. ,    1. ],
       [   0. ,  130.5,  -13.5,  144. ,  -65.5,  144. ,  -15.5,  -88. ],
       [   0. ,  -59.5,   36.5,  -65.5,   49. ,  -91. ,  -47.5,  -59.5],
       [   0. ,  137. ,  -15.5,  144. ,  -91. ,  169. ,  -55.5,  -97. ],
       [   0. ,  -11.5,  -19. ,  -15.5,  -47.5,  -55.5,   81. , -349. ],
       [   0. ,  -79. ,    1. ,  -88. ,  -59.5,  -97. , -349. ,  121. ]])

In [37]:
eigVal, eigVec = np.linalg.eig(M)#求特征值及特征向量


In [38]:
out=np.zeros((8, 4))

out

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
eigVal[2]*eigVec[2]


array([ -8.48963846, -23.49639791, -10.93447882, 223.57338762,
       -83.12626533, 312.26652261,  22.88966511,   0.        ])

In [ ]:
out[:,1]=eigVal[3]*eigVec[3],
out[:,2]=eigVal[4]*eigVec[4],
out[:,3]=eigVal[6]*eigVec[6]