In [10]:
import numpy as np
D = [[0,5,12],
[5,0,13],
[12,13,0]]

In [11]:
M=np.zeros_like(D, float)

In [19]:
for i in range(3):
    for j in range(3):
        d_1j=D[0][j]
        d_i1=D[i][0]
        d_ij=D[i][j]
        M[i][j]=1/2*(d_1j**2+d_i1**2-d_ij**2)

In [20]:
M

array([[  0.,   0.,   0.],
       [  0.,  25.,   0.],
       [  0.,   0., 144.]])

In [21]:
eigVal, eigVec = np.linalg.eig(M)#求特征值及特征向量
eigVal, eigVec

(array([  0.,  25., 144.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [27]:
np.sqrt(eigVal[1]*eigVec[1]), np.sqrt(eigVal[2]*eigVec[2])

(array([0., 5., 0.]), array([ 0.,  0., 12.]))

array([ 0.,  5., 12.])