https://blog.csdn.net/zhangweiguo_717/article/details/69663452 

https://github.com/heucoder/dimensionality_reduction_alo_codes/tree/master/codes/MDS 

In [102]:
import numpy as np
    
def D2B(D):
    D = np.asarray(D)
    DSquare = D ** 2
    totalMean = np.mean(DSquare)
    columnMean = np.mean(DSquare, axis = 0)
    rowMean = np.mean(DSquare, axis = 1)
    B = np.zeros(DSquare.shape)
    for i in range(B.shape[0]):
        for j in range(B.shape[1]):
            B[i][j] = -0.5 * (DSquare[i][j] - rowMean[i] - columnMean[j] + totalMean)
    return B


def MDS(D,d):
    B = D2B(D)
    eigVal, eigVec = np.linalg.eig(B)#求特征值及特征向量
    #对特征值进行排序，得到排序索引
    eigValSorted_indices = np.argsort(eigVal)
    #提取d个最大特征向量
    topd_eigVec = eigVec[:,eigValSorted_indices[:-d-1:-1]] #-d-1前加:才能向左切
    X = np.dot(topd_eigVec, np.sqrt(np.diag(eigVal[:-d-1:-1])))
    return X


In [103]:
# D = [[0,587,1212,701,1936,604,748,2139,2182,543],
# [587,0,920,940,1745,1188,713,1858,1737,597],
# [1212,920,0,879,831,1726,1631,949,1021,1494],
# [701,940,879,0,1374,968,1420,1645,1891,1220],
# [1936,1745,831,1374,0,2339,2451,347,959,2300],
# [604,1188,1726,968,2339,0,1092,2594,2734,923],
# [748,713,1631,1420,2451,1092,0,2571,2408,205],
# [2139,1858,949,1645,347,2594,2571,0,678,2442],
# [2182,1737,1021,1891,959,2734,2408,678,0,2329],
# [543,597,1494,1220,2300,923,205,2442,2329,0]]

DM = [[0,11,5,12,7,13,9,11],
[11,0,13,2,17,4,15,20],
[5,13,0,14,1,15,12,12],
[12,2,14,0,18,5,16,21],
[7,17,1,18,0,20,15,17],
[13,4,15,5,20,0,19,22],
[9,15,12,16,15,19,0,30],
[11,20,12,21,17,22,30,0]]

# DM = [[0,1,2,3,4,5,6,7],
# [1,0,1,2,3,4,5,6],
# [2,1,0,1,2,3,4,5],
# [3,2,1,0,1,2,3,4],
# [4,3,2,1,0,1,2,3],
# [5,4,3,2,1,0,1,2],
# [6,5,4,3,2,1,0,1],
# [7,6,5,4,3,2,1,0]]


DM

[[0, 11, 5, 12, 7, 13, 9, 11],
 [11, 0, 13, 2, 17, 4, 15, 20],
 [5, 13, 0, 14, 1, 15, 12, 12],
 [12, 2, 14, 0, 18, 5, 16, 21],
 [7, 17, 1, 18, 0, 20, 15, 17],
 [13, 4, 15, 5, 20, 0, 19, 22],
 [9, 15, 12, 16, 15, 19, 0, 30],
 [11, 20, 12, 21, 17, 22, 30, 0]]

In [104]:
X = MDS(DM,2)

X

d:\program\python\lib\site-packages\ipykernel_launcher.py:23: RuntimeWarning: invalid value encountered in sqrt


array([[-0.09628835,         nan],
       [ 0.20654759,         nan],
       [-0.15530087,         nan],
       [ 0.23198924,         nan],
       [-0.18642594,         nan],
       [ 0.23300712,         nan],
       [ 0.44626964,         nan],
       [-0.67979843,         nan]])

In [105]:

# D=np.array([[0,411,213,219,296,397],
#             [411,0,204,203,120,152],
#             [213,204,0,73,136,245],
#             [219,203,73,0,90,191],
#             [296,120,136,90,0,109],
#             [ 397,152,245,191,109,0]])

D=np.array([[0,11,5,12,7,13,9,11],
[11,0,13,2,17,4,15,20],
[5,13,0,14,1,15,12,12],
[12,2,14,0,18,5,16,21],
[7,17,1,18,0,20,15,17],
[13,4,15,5,20,0,19,22],
[9,15,12,16,15,19,0,30],
[11,20,12,21,17,22,30,0]])


In [134]:
import numpy as np

d_reduced=2

N = D.shape[0]
T = np.zeros((N,N))

#solution 1
#ss = 1.0/N**2*np.sum(D**2)
#for i in range(N):
#    for j in range(i,N):       
#        T[i,j] = T[j,i] = -0.5*(D[i,j]**2 -1.0/N*np.dot(D[i,:],D[i,:]) -1.0/N*np.dot(D[:,j],D[:,j])+ss)

#solution 2
#K = np.dot(D,np.transpose(D))
D2 = D**2
H = np.eye(N) - 1/N
T = -0.5*np.dot(np.dot(H,D2),H)

eigVal,eigVec = np.linalg.eig(T) 
X = np.dot(eigVec[:,:d_reduced],np.diag(np.sqrt(eigVal[:d_reduced]))) 

print('original distance','\tnew distance')
for i in range(N):
    for j in range(i+1,N):
        print(np.str(D[i,j]),'\t\t',np.str("%.4f"%np.linalg.norm(X[i]-X[j])))


original distance 	new distance
11 		 11.1509
5 		 1.9924
12 		 12.0990
7 		 5.7597
13 		 13.9689
9 		 14.5169
11 		 15.4821
13 		 13.1381
2 		 0.9481
17 		 16.7195
4 		 3.1120
15 		 16.3902
20 		 20.9837
14 		 14.0860
1 		 3.9962
15 		 15.9317
12 		 15.1980
12 		 15.0122
18 		 17.6633
5 		 2.3152
16 		 16.8909
21 		 21.6463
20 		 19.6372
15 		 15.0131
17 		 17.0227
19 		 19.1059
22 		 22.0291
30 		 29.9980


In [107]:
from sklearn.datasets import load_digits
from sklearn.manifold import MDS
X, _ = load_digits(return_X_y=True)
X.shape
embedding = MDS(n_components=2)
X_transformed = embedding.fit_transform(X[:100])
X_transformed.shape

(100, 2)

In [116]:
def my_mds(data, n_dims):
    '''
    :param data: (n_samples, n_features)
    :param n_dims: target n_dims
    :return: (n_samples, n_dims)
    '''

    n, n = data.shape
    dist = data
    print(dist.shape)
    dist[dist < 0 ] = 0
    T1 = np.ones((n,n))*np.sum(dist)/n**2
    T2 = np.sum(dist, axis = 1, keepdims=True)/n
    T3 = np.sum(dist, axis = 0, keepdims=True)/n

    B = -(T1 - T2 - T3 + dist)/2

    eig_val, eig_vector = np.linalg.eig(B)
    index_ = np.argsort(-eig_val)[:n_dims]
    picked_eig_val = eig_val[index_].real
    picked_eig_vector = eig_vector[:, index_]
    # print(picked_eig_vector.shape, picked_eig_val.shape)
    return picked_eig_vector*picked_eig_val**(0.5)


In [121]:
from sklearn.datasets import load_iris
D=np.array([[0,11,5,12,7,13,9,11],
[11,0,13,2,17,4,15,20],
[5,13,0,14,1,15,12,12],
[12,2,14,0,18,5,16,21],
[7,17,1,18,0,20,15,17],
[13,4,15,5,20,0,19,22],
[9,15,12,16,15,19,0,30],
[11,20,12,21,17,22,30,0]])


In [131]:
data_1 = my_mds(D, 8)
data_1

(8, 8)


array([[-8.84816047e-01,  2.58868830e-01, -7.51577517e-01,
        -4.08441956e-01, -1.02038597e+00, -3.07004795e-02,
        -3.55506757e-02, -4.59876586e-09],
       [ 1.85432373e+00, -3.19262107e-01,  1.65282942e-01,
         4.87679499e-01, -2.27419721e-02, -7.54147188e-01,
        -1.22596832e-02, -4.59876586e-09],
       [-1.46712611e+00,  3.16030066e-01,  8.38763112e-01,
        -3.04242312e-02,  3.82181188e-01,  6.01347451e-02,
        -1.36154862e-01, -4.59876586e-09],
       [ 1.95084927e+00, -3.43476549e-01,  1.99980162e-01,
         8.77868476e-01, -2.12489401e-01,  5.87706453e-01,
        -3.90129982e-03, -4.59876586e-09],
       [-1.84705085e+00,  6.79032286e-01,  1.44286973e+00,
         1.20398521e-01, -1.35735706e-01, -4.01983307e-02,
         1.04447769e-01, -4.59876586e-09],
       [ 2.05901434e+00, -6.11164819e-01,  4.06328831e-01,
        -1.23908845e+00,  2.11625293e-01,  1.27287240e-01,
         2.25139770e-02, -4.59876586e-09],
       [ 3.15333502e-02,  2.604517

In [135]:
def cal_B(D):
    (n1, n2) = D.shape
    DD = np.square(D)                    # 矩阵D 所有元素平方
    Di = np.sum(DD, axis=1) / n1         # 计算dist(i.)^2
    Dj = np.sum(DD, axis=0) / n1         # 计算dist(.j)^2
    Dij = np.sum(DD) / (n1 ** 2)         # 计算dist(ij)^2
    B = np.zeros((n1, n1))
    for i in range(n1):
        for j in range(n2):
            B[i, j] = (Dij + DD[i, j] - Di[i] - Dj[j]) / (-2)   # 计算b(ij)
    return B

In [146]:
def MDS(D, n):
    B = cal_B(D)
    Be, Bv = np.linalg.eigh(B)             # Be矩阵B的特征值，Bv归一化的特征向量
    # print numpy.sum(B-numpy.dot(numpy.dot(Bv,numpy.diag(Be)),Bv.T))
    Be_sort = np.argsort(-Be)
    Be = Be[Be_sort]                          # 特征值从大到小排序
    Bv = Bv[:, Be_sort]                       # 归一化特征向量
    Bez = np.diag(Be[0:n])                 # 前n个特征值对角矩阵
    # print Bez
    Bvz = Bv[:, 0:n]                          # 前n个归一化特征向量
    Z = np.dot(np.sqrt(Bez), Bvz.T).T
    # print(Z)
    return Z

In [147]:
D=np.array([[0,11,5,12,7,13,9,11],
[11,0,13,2,17,4,15,20],
[5,13,0,14,1,15,12,12],
[12,2,14,0,18,5,16,21],
[7,17,1,18,0,20,15,17],
[13,4,15,5,20,0,19,22],
[9,15,12,16,15,19,0,30],
[11,20,12,21,17,22,30,0]])



In [145]:
Z=MDS(D,5)
Z

array([[-2.27376653e+00,  2.86337203e+00, -3.64048874e+00,
         3.20279834e-01, -7.84745019e-02],
       [ 4.87744340e+00, -5.69243782e+00,  2.32276048e-01,
        -9.26669561e-01,  7.58012457e-01],
       [-3.66729633e+00,  4.28734962e+00,  1.36202129e+00,
         8.18788234e-01, -6.37362589e-02],
       [ 5.47822616e+00, -6.42593635e+00,  5.69202334e-01,
        -2.26075289e+00, -5.21981848e-01],
       [-4.40228801e+00,  8.21535769e+00,  3.62569583e+00,
        -3.57450664e-01,  2.83641696e-02],
       [ 5.50226256e+00, -8.74106092e+00,  9.89014866e-01,
         2.61501071e+00, -1.47119449e-01],
       [ 1.05382734e+01,  9.68920616e+00, -1.78193529e+00,
         4.94619922e-02,  3.19058458e-03],
       [-1.60528546e+01, -4.19585041e+00, -1.35578633e+00,
        -2.58667657e-01,  2.17448464e-02]])