In [1]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

d:\program\python\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
d:\program\python\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
d:\program\python\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)


[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 10206220887247036732
]


NameError: name 'tf' is not defined

In [ ]:
import tensorflow as tf
# tf.test.is_built_with_cuda()
# tf.test.is_built_with_gpu_support()



In [ ]:
import tensorflow as tf
with tf.compat.v1.Session() as ses:
    a=tf.constant(2)
    print(sess.run(a))

In [2]:
import tensorflow as tf
tf.test.is_gpu_available(
    cuda_only=False,
    min_cuda_compute_capability=None
)
# tf.test.gpu_device_name()
# tf.config.list_physical_devices('GPU')

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [3]:
import torch
torch.cuda.is_available()
# torch.cuda.device_count()
# torch.cuda.get_device_name(0)
# torch.cuda.current_device()

True

In [4]:
import numpy as np
test = np.random.random((4, 2, 3))
print(test)

[[[0.94232276 0.24367749 0.80309041]
  [0.59927321 0.80359047 0.0198291 ]]

 [[0.65577551 0.44704665 0.3515786 ]
  [0.61304619 0.89991561 0.42708159]]

 [[0.57993832 0.02432251 0.85871053]
  [0.02625928 0.86192649 0.32111149]]

 [[0.83806708 0.97700969 0.99870242]
  [0.73241313 0.45664349 0.20653413]]]


In [27]:
# 导入 keras 相关模块
from keras.models import Sequential
from keras.layers import LSTM, Dense
import numpy as np
# 指定数据维度和时间步等参数
data_dim = 16
timesteps = 8
num_classes = 10
# 搭建一个 LSTM 多分类过程
model = Sequential()
model.add(LSTM(32, return_sequences=True,
               input_shape=(timesteps, data_dim)))  
model.add(LSTM(32, return_sequences=True))  
model.add(LSTM(32))  
model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])
# 生成模拟训练数据
x_train = np.random.random((1000, timesteps, data_dim))
y_train = np.random.random((1000, num_classes))
# 生成模型验证数据
x_val = np.random.random((100, timesteps, data_dim))
y_val = np.random.random((100, num_classes))
# 模型训练
model.fit(x_train, y_train, batch_size=64, epochs=5, validation_data=(x_val, y_val))

Train on 1000 samples, validate on 100 samples
Epoch 1/5
1000/1000 [==============================] - 1s 850us/step - loss: 11.8885 - accuracy: 0.1050 - val_loss: 12.4829 - val_accuracy: 0.0700
Epoch 2/5
1000/1000 [==============================] - 0s 136us/step - loss: 12.9973 - accuracy: 0.0950 - val_loss: 12.9876 - val_accuracy: 0.1300
Epoch 3/5
1000/1000 [==============================] - 0s 116us/step - loss: 13.2360 - accuracy: 0.0960 - val_loss: 13.1013 - val_accuracy: 0.1300
Epoch 4/5
1000/1000 [==============================] - 0s 117us/step - loss: 13.3028 - accuracy: 0.0960 - val_loss: 13.1214 - val_accuracy: 0.1300
Epoch 5/5
1000/1000 [==============================] - 0s 117us/step - loss: 13.2766 - accuracy: 0.0960 - val_loss: 13.0611 - val_accuracy: 0.1300


In [4]:
# 导入 keras 相关模块
from keras.models import Sequential
from keras.layers import LSTM, Dense
import numpy as np
# 指定数据维度和时间步等参数
data_dim = 16
timesteps = 8
num_classes = 10
# 搭建一个 LSTM 多分类过程
model = Sequential()
model.add(LSTM(32, return_sequences=True,
               input_shape=(timesteps, data_dim)))  
model.add(LSTM(32, return_sequences=True))  
model.add(LSTM(32))  
model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])
# 生成模拟训练数据
x_train = np.random.random((10, timesteps, data_dim))
y_train = np.random.random((10, num_classes))
# 生成模型验证数据
x_val = np.random.random((1, timesteps, data_dim))
y_val = np.random.random((1, num_classes))
# 模型训练
model.fit(x_train, y_train, batch_size=64, epochs=5, validation_data=(x_val, y_val))

Train on 10 samples, validate on 1 samples
Epoch 1/5
10/10 [==============================] - 1s 66ms/step - loss: 10.7980 - accuracy: 0.1000 - val_loss: 13.1841 - val_accuracy: 0.0000e+00
Epoch 2/5
10/10 [==============================] - 0s 2ms/step - loss: 10.7919 - accuracy: 0.3000 - val_loss: 13.2189 - val_accuracy: 0.0000e+00
Epoch 3/5
10/10 [==============================] - 0s 2ms/step - loss: 10.7897 - accuracy: 0.3000 - val_loss: 13.2607 - val_accuracy: 0.0000e+00
Epoch 4/5
10/10 [==============================] - 0s 2ms/step - loss: 10.7892 - accuracy: 0.3000 - val_loss: 13.3122 - val_accuracy: 0.0000e+00
Epoch 5/5
10/10 [==============================] - 0s 2ms/step - loss: 10.7917 - accuracy: 0.3000 - val_loss: 13.3765 - val_accuracy: 0.0000e+00


In [29]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM

import numpy as np
model = Sequential()
model.add(Dense(32, input_dim=32))
# now: model.output_shape == (None, 32)
# note: `None` is the batch dimension

model.add(RepeatVector(3))
# now: model.output_shape == (None, 3, 32)

NameError: name 'RepeatVector' is not defined

In [30]:
'''
#Trains a Bidirectional LSTM on the IMDB sentiment classification task.

Output after 4 epochs on CPU: ~0.8146
Time per epoch on CPU (Core i7): ~150s.
'''

from __future__ import print_function
import numpy as np

from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Dropout, Embedding, LSTM, Bidirectional
from keras.datasets import imdb


max_features = 20000
# cut texts after this number of words
# (among top max_features most common words)
maxlen = 100
batch_size = 32

print('Loading data...')
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)
print(len(x_train), 'train sequences')
print(len(x_test), 'test sequences')

print('Pad sequences (samples x time)')
x_train = sequence.pad_sequences(x_train, maxlen=maxlen)
x_test = sequence.pad_sequences(x_test, maxlen=maxlen)
print('x_train shape:', x_train.shape)
print('x_test shape:', x_test.shape)
y_train = np.array(y_train)
y_test = np.array(y_test)

model = Sequential()
model.add(Embedding(max_features, 128, input_length=maxlen))
model.add(Bidirectional(LSTM(64)))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

# try using different optimizers and different optimizer configs
model.compile('adam', 'binary_crossentropy', metrics=['accuracy'])

print('Train...')
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=4,
          validation_data=[x_test, y_test])


Loading data...
25000 train sequences
25000 test sequences
Pad sequences (samples x time)
x_train shape: (25000, 100)
x_test shape: (25000, 100)
Train...


d:\program\python\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:433: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 25000 samples, validate on 25000 samples
Epoch 1/4
 8480/25000 [=========>....................] - ETA: 41s - loss: 0.5171 - accuracy: 0.7289

KeyboardInterrupt: 

In [2]:
'''
#Example script to generate text from Nietzsche's writings.

At least 20 epochs are required before the generated text
starts sounding coherent.

It is recommended to run this script on GPU, as recurrent
networks are quite computationally intensive.

If you try this script on new data, make sure your corpus
has at least ~100k characters. ~1M is better.
'''

from __future__ import print_function
from keras.callbacks import LambdaCallback
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.optimizers import RMSprop
from keras.utils.data_utils import get_file
import numpy as np
import random
import sys
import io

path = get_file(
    'nietzsche.txt',
    origin='https://s3.amazonaws.com/text-datasets/nietzsche.txt')
with io.open(path, encoding='utf-8') as f:
    text = f.read().lower()
print('corpus length:', len(text))

chars = sorted(list(set(text)))
print('total chars:', len(chars))
char_indices = dict((c, i) for i, c in enumerate(chars))
indices_char = dict((i, c) for i, c in enumerate(chars))

# cut the text in semi-redundant sequences of maxlen characters
maxlen = 40
step = 3
sentences = []
next_chars = []
for i in range(0, len(text) - maxlen, step):
    sentences.append(text[i: i + maxlen])
    next_chars.append(text[i + maxlen])
print('nb sequences:', len(sentences))

print('Vectorization...')
x = np.zeros((len(sentences), maxlen, len(chars)), dtype=np.bool)
y = np.zeros((len(sentences), len(chars)), dtype=np.bool)
for i, sentence in enumerate(sentences):
    for t, char in enumerate(sentence):
        x[i, t, char_indices[char]] = 1
    y[i, char_indices[next_chars[i]]] = 1


# build the model: a single LSTM
print('Build model...')
model = Sequential()
model.add(LSTM(128, input_shape=(maxlen, len(chars))))
model.add(Dense(len(chars), activation='softmax'))

optimizer = RMSprop(learning_rate=0.01)
model.compile(loss='categorical_crossentropy', optimizer=optimizer)


def sample(preds, temperature=1.0):
    # helper function to sample an index from a probability array
    preds = np.asarray(preds).astype('float64')
    preds = np.log(preds) / temperature
    exp_preds = np.exp(preds)
    preds = exp_preds / np.sum(exp_preds)
    probas = np.random.multinomial(1, preds, 1)
    return np.argmax(probas)


def on_epoch_end(epoch, _):
    # Function invoked at end of each epoch. Prints generated text.
    print()
    print('----- Generating text after Epoch: %d' % epoch)

    start_index = random.randint(0, len(text) - maxlen - 1)
    for diversity in [0.2, 0.5, 1.0, 1.2]:
        print('----- diversity:', diversity)

        generated = ''
        sentence = text[start_index: start_index + maxlen]
        generated += sentence
        print('----- Generating with seed: "' + sentence + '"')
        sys.stdout.write(generated)

        for i in range(400):
            x_pred = np.zeros((1, maxlen, len(chars)))
            for t, char in enumerate(sentence):
                x_pred[0, t, char_indices[char]] = 1.

            preds = model.predict(x_pred, verbose=0)[0]
            next_index = sample(preds, diversity)
            next_char = indices_char[next_index]

            sentence = sentence[1:] + next_char

            sys.stdout.write(next_char)
            sys.stdout.flush()
        print()

print_callback = LambdaCallback(on_epoch_end=on_epoch_end)

model.fit(x, y,
          batch_size=128,
          epochs=60,
          callbacks=[print_callback])


606208/600901 [==============================] - 3s 4us/step
corpus length: 600893
total chars: 57
nb sequences: 200285
Vectorization...
Build model...
Epoch 1/60
200285/200285 [==============================] - 97s 483us/step - loss: 1.9774

----- Generating text after Epoch: 0
----- diversity: 0.2
----- Generating with seed: "danger, about which the ascetic might
wi"
danger, about which the ascetic might
with the sense the superien and the acting and the persons and the may the supersent and the superien and the subjection and the say the suppersion and and the moral say the been the love morals the say the say the supersion and the may be a morals the presenting the means the superien and the philosophers and the suppentitical the say the may the powerful the may the supersence and the suppessitica
----- diversity: 0.5
----- Generating with seed: "danger, about which the ascetic might
wi"
danger, about which the ascetic might
with the whild be the sufferine of the more reading and s

KeyboardInterrupt: 