# Data Types in Python
By default Python have these data types:  

+ strings - used to represent text data, the text is given under quote marks. eg. "ABCD"  
+ integer - used to represent integer numbers. eg. -1, -2, -3   
+ float - used to represent real numbers. eg. 1.2, 42.42  
+ boolean - used to represent True or False.  
+ complex - used to represent a number in complex plain. eg. 1.0 + 2.0j, 1.5 + 2.5j  

# Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

+ i - integer  
+ b - boolean  
+ u - unsigned integer  
+ f - float  
+ c - complex float  
+ m - timedelta  
+ M - datetime  
+ O - object  
+ S - string  
+ U - unicode string  
+ V - fixed chunk of memory for other type ( void )  

# Checking the Data Type of an Array

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [10]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4') # i4 - data type 4 bytes integer

print(arr)
print(arr.dtype)  

[1 2 3 4]
int32


# Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [16]:
import numpy as np

arr = np.array([1.9, 2.1, 3.8])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [17]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [18]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
