# Random Numbers in NumPy
Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

# Pseudo Random and True Random.
Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless its related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).

In this tutorial we will be using pseudo random numbers.

In [4]:
from numpy import random

x = random.randint(100)

print(x)

5


In [5]:
from numpy import random

x = random.rand()

print(x)

0.4651269624943347


In [6]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[50 15 45 14 55]


In [7]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[65  1 64 35 66]
 [44 41 88 14 79]
 [12 11 12 98 88]]


In [8]:
from numpy import random

x = random.rand(5)

print(x)

[0.08625977 0.82676641 0.33013027 0.72419938 0.91912915]


In [9]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.28907283 0.88744284 0.78689396 0.82200294 0.821209  ]
 [0.32253471 0.18527722 0.5929231  0.21428077 0.08133766]
 [0.4995655  0.88048841 0.21162979 0.22985477 0.06879399]]


# Generate Random Number From Array
The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

In [11]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

9


In [12]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 7 3 7 7]
 [7 9 5 5 5]
 [3 5 7 5 3]]
