## Tensor

In [58]:
print(1)

1


In [59]:
import torch
x = torch.Tensor(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [60]:
print(x.size())

torch.Size([2, 3])


In [61]:
y = torch.rand(2, 3)
print(x + y)

tensor([[0.9438, 0.2331, 0.3797],
        [0.4541, 0.3964, 0.2601]])


In [62]:
result = torch.Tensor(2, 3)
torch.add(x, y, out = result)
print(result)

tensor([[0.9438, 0.2331, 0.3797],
        [0.4541, 0.3964, 0.2601]])


In [63]:
a = torch.ones(5).numpy()
print(a)

[1. 1. 1. 1. 1.]


In [64]:
import numpy as np
print(torch.from_numpy(np.ones(5)))

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [65]:
example_tensor = torch.Tensor(
    [
     [[1, 2], [3, 4]], 
     [[5, 6], [7, 8]], 
     [[9, 0], [1, 2]]
    ]
)
example_tensor

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]],

        [[9., 0.],
         [1., 2.]]])

In [66]:
example_tensor.device

device(type='cpu')

In [67]:
example_tensor.shape

torch.Size([3, 2, 2])

In [68]:
print("shape[0] =", example_tensor.shape[0])
print("size(1) =", example_tensor.size(1))

shape[0] = 3
size(1) = 2


In [69]:
print("Rank =", len(example_tensor.shape))
print("Number of elements =", example_tensor.numel())

Rank = 3
Number of elements = 12


In [70]:
example_tensor[1]

tensor([[5., 6.],
        [7., 8.]])

In [71]:
example_tensor[1, 1, 0]

tensor(7.)

In [72]:
example_scalar = example_tensor[1, 1, 0]
example_scalar.item()

7.0

In [73]:
example_tensor[:, 0, 0]

tensor([1., 5., 9.])

In [74]:
torch.ones_like(example_tensor)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [75]:
torch.zeros_like(example_tensor)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [76]:
torch.randn_like(example_tensor)

tensor([[[ 1.5149,  0.2575],
         [-2.1353, -0.2547]],

        [[-0.8479, -0.0924],
         [-0.5741, -0.9052]],

        [[ 1.5552, -0.9232],
         [ 0.1042, -0.2715]]])

In [77]:
torch.randn(2, 2, device='cpu') # Alternatively, for a GPU tensor, you'd use device='cuda'

tensor([[ 1.8888, -1.8281],
        [-0.5100, -0.0032]])

In [78]:
(example_tensor - 5) * 2

tensor([[[ -8.,  -6.],
         [ -4.,  -2.]],

        [[  0.,   2.],
         [  4.,   6.]],

        [[  8., -10.],
         [ -8.,  -6.]]])

In [80]:
print("Mean:", example_tensor.mean())
print("Stdev:", example_tensor.std())

Mean: tensor(4.)
Stdev: tensor(2.9848)


### Switch to GPU

In [79]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

### Variable

In [10]:
from torch.autograd import Variable
x = Variable(torch.ones(2, 3), requires_grad = True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [14]:
y = x + 2
z = y * y * 5
out = z.mean()
out.backward()
print(x.grad)

tensor([[5., 5., 5.],
        [5., 5., 5.]])


## keras

In [46]:
tt.to_csv("../data/test.csv")

In [4]:
import os
path = '../data'
os.listdir(path)

['.ipynb_checkpoints',
 'Divvy_Trips_2019_Q4',
 'Geolife',
 'T-drive_taxi',
 'test.csv',
 'test.xlsx']

In [3]:
import torch
torch.cuda.is_available()

d:\program\python\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
d:\program\python\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
d:\program\python\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)


True

In [1]:
try:
    from google.colab import drive
    %tensorflow_version 2.x
    COLAB = True
    print("Note: using Google CoLab")
except:
    print("Note: not using Google CoLab")
    COLAB = False
    

Note: not using Google CoLab


## Define Models

In [1]:
import torch
from torch import nn

## `nn.Linear`

To create a linear layer, you need to pass it the number of input dimensions and the number of output dimensions. The linear object initialized as `nn.Linear(10, 2)` will take in a $n\times10$ matrix and return an $n\times2$ matrix, where all $n$ elements have had the same linear transformation performed. For example, you can initialize a linear layer which performs the operation $Ax + b$, where $A$ and $b$ are initialized randomly when you generate the [`nn.Linear()`](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html) object. 

In [81]:
linear = nn.Linear(10, 2)
example_input = torch.randn(3, 10)
example_output = linear(example_input)
example_output

tensor([[-0.5007,  0.0211],
        [ 0.1089, -0.3218],
        [ 0.6021,  0.7772]], grad_fn=<AddmmBackward>)

## `nn.ReLU`

[`nn.ReLU()`](https://pytorch.org/docs/stable/generated/torch.nn.ReLU.html) will create an object that, when receiving a tensor, will perform a ReLU activation function. This will be reviewed further in lecture, but in essence, a ReLU non-linearity sets all negative numbers in a tensor to zero. In general, the simplest neural networks are composed of series of linear transformations, each followed by activation functions. 


In [82]:
relu = nn.ReLU()
relu_output = relu(example_output)
relu_output

tensor([[0.0000, 0.0211],
        [0.1089, 0.0000],
        [0.6021, 0.7772]], grad_fn=<ReluBackward0>)

## `nn.BatchNorm1d`

[`nn.BatchNorm1d`](https://pytorch.org/docs/stable/generated/torch.nn.BatchNorm1d.html) is a normalization technique that will rescale a batch of $n$ inputs to have a consistent mean and standard deviation between batches.  

As indicated by the `1d` in its name, this is for situations where you expects a set of inputs, where each of them is a flat list of numbers. In other words, each input is a vector, not a matrix or higher-dimensional tensor. For a set of images, each of which is a higher-dimensional tensor, you'd use [`nn.BatchNorm2d`](https://pytorch.org/docs/stable/generated/torch.nn.BatchNorm2d.html), discussed later on this page.

`nn.BatchNorm1d` takes an argument of the number of input dimensions of each object in the batch (the size of each example vector).

In [83]:
batchnorm = nn.BatchNorm1d(2)
batchnorm_output = batchnorm(relu_output)
batchnorm_output

tensor([[-0.9047, -0.6777],
        [-0.4889, -0.7361],
        [ 1.3936,  1.4138]], grad_fn=<NativeBatchNormBackward>)

## `nn.Sequential`

[`nn.Sequential`](https://pytorch.org/docs/stable/generated/torch.nn.Sequential.html) creates a single operation that performs a sequence of operations. For example, you can write a neural network layer with a batch normalization as

In [84]:
mlp_layer = nn.Sequential(
    nn.Linear(5, 2),
    nn.BatchNorm1d(2),
    nn.ReLU()
)

test_example = torch.randn(5,5) + 1
print("input: ")
print(test_example)
print("output: ")
print(mlp_layer(test_example))

input: 
tensor([[ 1.2667, -0.2178, -0.4638,  1.7108,  0.9415],
        [-1.3102, -0.1033,  2.2152, -1.0444,  2.3017],
        [-0.4778,  1.7618,  0.7225,  0.8321,  1.0436],
        [ 0.4167, -0.3455,  0.7873,  1.0230, -0.9606],
        [ 1.2976,  0.7832,  0.2993,  2.0219, -0.4548]])
output: 
tensor([[0.2132, 0.0000],
        [1.0309, 1.6357],
        [0.7094, 0.0000],
        [0.0000, 0.4216],
        [0.0000, 0.0000]], grad_fn=<ReluBackward0>)


# Optimization

One of the most important aspects of essentially any machine learning framework is its automatic differentiation library. 

## Optimizers

To create an optimizer in PyTorch, you'll need to use the `torch.optim` module, often imported as `optim`. [`optim.Adam`](https://pytorch.org/docs/stable/optim.html#torch.optim.Adam) corresponds to the Adam optimizer. To create an optimizer object, you'll need to pass it the parameters to be optimized and the learning rate, `lr`, as well as any other parameters specific to the optimizer.

For all `nn` objects, you can access their parameters as a list using their `parameters()` method, as follows:

In [85]:
import torch.optim as optim
adam_opt = optim.Adam(mlp_layer.parameters(), lr=1e-1)

## Training Loop

A (basic) training step in PyTorch consists of four basic parts:


1.   Set all of the gradients to zero using `opt.zero_grad()`
2.   Calculate the loss, `loss`
3.   Calculate the gradients with respect to the loss using `loss.backward()`
4.   Update the parameters being optimized using `opt.step()`

That might look like the following code (and you'll notice that if you run it several times, the loss goes down):


In [87]:
train_example = torch.randn(100,5) + 1
adam_opt.zero_grad()

# We'll use a simple loss function of mean distance from 1
# torch.abs takes the absolute value of a tensor
cur_loss = torch.abs(1 - mlp_layer(train_example)).mean()

cur_loss.backward()
adam_opt.step()
print(cur_loss)

tensor(0.7739, grad_fn=<MeanBackward0>)


## `requires_grad_()`

You can also tell PyTorch that it needs to calculate the gradient with respect to a tensor that you created by saying `example_tensor.requires_grad_()`, which will change it in-place. This means that even if PyTorch wouldn't normally store a grad for that particular tensor, it will for that specified tensor. 

## `with torch.no_grad():`

PyTorch will usually calculate the gradients as it proceeds through a set of operations on tensors. This can often take up unnecessary computations and memory, especially if you're performing an evaluation. However, you can wrap a piece of code with `with torch.no_grad()` to prevent the gradients from being calculated in a piece of code. 


## `detach():`

Sometimes, you want to calculate and use a tensor's value without calculating its gradients. For example, if you have two models, A and B, and you want to directly optimize the parameters of A with respect to the output of B, without calculating the gradients through B, then you could feed the detached output of B to A. There are many reasons you might want to do this, including efficiency or cyclical dependencies (i.e. A depends on B depends on A).

# New `nn` Classes

You can also create new classes which extend the `nn` module. For these classes, all class attributes, as in `self.layer` or `self.param` will automatically treated as parameters if they are themselves `nn` objects or if they are tensors wrapped in `nn.Parameter` which are initialized with the class. 

The `__init__` function defines what will happen when the object is created. The first line of the init function of a class, for example, `WellNamedClass`, needs to be `super(WellNamedClass, self).__init__()`. 

The `forward` function defines what runs if you create that object `model` and pass it a tensor `x`, as in `model(x)`. If you choose the function signature, `(self, x)`, then each call of the forward function, gets two pieces of information: `self`, which is a reference to the object with which you can access all of its parameters, and `x`, which is the current tensor for which you'd like to return `y`.

One class might look like the following:

In [88]:
class ExampleModule(nn.Module):
    def __init__(self, input_dims, output_dims):
        super(ExampleModule, self).__init__()
        self.linear = nn.Linear(input_dims, output_dims)
        self.exponent = nn.Parameter(torch.tensor(1.))

    def forward(self, x):
        x = self.linear(x)

        # This is the notation for element-wise exponentiation, 
        # which matches python in general
        x = x ** self.exponent 
        
        return x

In [89]:
example_model = ExampleModule(10, 2)
list(example_model.parameters())

[Parameter containing:
 tensor(1., requires_grad=True),
 Parameter containing:
 tensor([[ 0.2586, -0.0927, -0.1440,  0.1028,  0.2975, -0.2939,  0.2119,  0.2294,
          -0.0067,  0.2339],
         [ 0.3079, -0.2337, -0.0520, -0.2522,  0.1193,  0.2710,  0.0601,  0.1526,
          -0.2773,  0.0365]], requires_grad=True),
 Parameter containing:
 tensor([ 0.1287, -0.2860], requires_grad=True)]

In [90]:
list(example_model.named_parameters())

[('exponent',
  Parameter containing:
  tensor(1., requires_grad=True)),
 ('linear.weight',
  Parameter containing:
  tensor([[ 0.2586, -0.0927, -0.1440,  0.1028,  0.2975, -0.2939,  0.2119,  0.2294,
           -0.0067,  0.2339],
          [ 0.3079, -0.2337, -0.0520, -0.2522,  0.1193,  0.2710,  0.0601,  0.1526,
           -0.2773,  0.0365]], requires_grad=True)),
 ('linear.bias',
  Parameter containing:
  tensor([ 0.1287, -0.2860], requires_grad=True))]

In [91]:
input = torch.randn(2, 10)
example_model(input)

tensor([[-0.8004, -0.8184],
        [-0.2952,  0.1076]], grad_fn=<PowBackward1>)

# 2D Operations

You won't need these for the first lesson, and the theory behind each of these will be reviewed more in later lectures, but here is a quick reference: 


*   2D convolutions: [`nn.Conv2d`](https://pytorch.org/docs/master/generated/torch.nn.Conv2d.html) requires the number of input and output channels, as well as the kernel size.
*   2D transposed convolutions (aka deconvolutions): [`nn.ConvTranspose2d`](https://pytorch.org/docs/master/generated/torch.nn.ConvTranspose2d.html) also requires the number of input and output channels, as well as the kernel size
*   2D batch normalization: [`nn.BatchNorm2d`](https://pytorch.org/docs/stable/generated/torch.nn.BatchNorm2d.html) requires the number of input dimensions
*   Resizing images: [`nn.Upsample`](https://pytorch.org/docs/master/generated/torch.nn.Upsample.html) requires the final size or a scale factor. Alternatively, [`nn.functional.interpolate`](https://pytorch.org/docs/stable/nn.functional.html#torch.nn.functional.interpolate) takes the same arguments. 



