## Tensor

In [ ]:
print(1)

In [ ]:
import torch
x = torch.Tensor(2, 3)
print(x)

In [ ]:
print(x.size())

In [ ]:
y = torch.rand(2, 3)
print(x + y)

In [6]:
result = torch.Tensor(2, 3)
torch.add(x, y, out = result)
print(result)

tensor([[3.4182e-02, 4.4377e+27, 1.9366e+31],
        [1.7106e-01, 1.0950e+21, 4.7566e-01]])


In [7]:
a = torch.ones(5).numpy()
print(a)

[1. 1. 1. 1. 1.]


In [8]:
import numpy as np
print(torch.from_numpy(np.ones(5)))

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### Switch to GPU

In [9]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

### Variable

In [10]:
from torch.autograd import Variable
x = Variable(torch.ones(2, 3), requires_grad = True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [14]:
y = x + 2
z = y * y * 5
out = z.mean()
out.backward()
print(x.grad)

tensor([[5., 5., 5.],
        [5., 5., 5.]])


## keras

In [46]:
tt.to_csv("../data/test.csv")

In [4]:
import os
path = '../data'
os.listdir(path)

['.ipynb_checkpoints',
 'Divvy_Trips_2019_Q4',
 'Geolife',
 'T-drive_taxi',
 'test.csv',
 'test.xlsx']

In [3]:
import torch
torch.cuda.is_available()

d:\program\python\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
d:\program\python\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
d:\program\python\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)


True

In [1]:
try:
    from google.colab import drive
    %tensorflow_version 2.x
    COLAB = True
    print("Note: using Google CoLab")
except:
    print("Note: not using Google CoLab")
    COLAB = False
    

Note: not using Google CoLab
